CREATE TABLE STUDENT(SID INT,SNAME VARCHAR(10), SCLASS VARCHAR(20));
INSERT INTO STUDENT VALUES(1,'RAM','FIRST');
INSERT INTO STUDENT VALUES(2,'RAJU','SECOND');
DECLARE
    STU_ID NUMBER;
    STU_NAME VARCHAR(20);
    CURSOR STU_CUR IS SELECT SID,SNAME FROM STUDENT WHERE SCLASS ='FIRST';
BEGIN
	OPEN STU_CUR;
LOOP
	FETCH STU_CUR INTO STU_ID,STU_NAME;
	EXIT WHEN STU_CUR%NOTFOUND;
	DBMS_OUTPUT.PUT_LINE('STUDENT ID IS ' || STU_ID || ' STUDENT NAME ' || STU_NAME);
END LOOP;
CLOSE STU_CUR;
END;
-- output
-- STUDENT ID IS 1 STUDENT NAME RAM
