CREATE TABLE SAILORS(SID INT PRIMARY KEY,SNAME VARCHAR(30),AGE INT,RATING INT);
CREATE TABLE BOATS(BID INT PRIMARY KEY, BNAME VARCHAR(30),COLOR VARCHAR(20));
CREATE TABLE RESERVES(SID INT,BID INT,DAY VARCHAR(20), FOREIGN KEY(SID) REFERENCES SAILORS(SID),FOREIGN KEY(BID) REFERENCES BOATS(BID));
INSERT INTO SAILORS VALUES(1,'KALYAN',18,10);
INSERT INTO SAILORS VALUES(2,'RAM', 19,9);
INSERT INTO SAILORS VALUES(3,'RAJU',20,8);
INSERT INTO BOATS VALUES(101,'MOTARBOAT','RED');
INSERT INTO BOATS VALUES(102,'SAILORSBOAT','GREEN');
INSERT INTO BOATS VALUES(103,'BOATNAME','BLUE');
INSERT INTO RESERVES VALUES(1,101,'MONDAY');
INSERT INTO RESERVES VALUES(2,102,'TUESDAY');
INSERT INTO RESERVES VALUES(3,103,'FRIDAY');
ALTER TABLE SAILORS
ADD CONSTRAINT UQ_RATING
UNIQUE(RATING);
SELECT S.SNAME FROM SAILORS S WHERE S.SID NOT IN(SELECT R.SID FROM RESERVES R WHERE R.BID=103);
SELECT S.SNAME FROM SAILORS S WHERE S.SID IN(SELECT R.SID FROM RESERVES R WHERE R.BID IN(SELECT B.BID FROM BOATS B WHERE B.COLOR='RED'));
SELECT * FROM SAILORS WHERE RATING > 7;
