-- plsql
CREATE OR REPLACE FUNCTION REVERSE_STRING(INPUT_STRING IN VARCHAR2)
	RETURN VARCHAR2 IS
	REVERSED VARCHAR(4000) :='';
BEGIN 
	FOR I IN REVERSE 1..LENGTH(INPUT_STRING) LOOP
		REVERSED := REVERSED || SUBSTR(INPUT_STRING,I,1);
	END LOOP;
	RETURN REVERSED;
END;
-- FUNCTION CREATED
CREATE TABLE EMP(EMPNO INT,ENAME VARCHAR(20),JOB VARCHAR(10),HIREDATE DATE,SALARY INT,DEPTNO INT);
CREATE TABLE DEPT(DEPTNO INT,DNAME VARCHAR(12),LOCATION VARCHAR(10));
