CREATE TABLE SAILORS(SID INT PRIMARY KEY,SNAME VARCHAR(30),AGE INT,RATING INT);
CREATE TABLE BOATS(BID INT PRIMARY KEY, BNAME VARCHAR(30),COLOR VARCHAR(20));
CREATE TABLE RESERVES(SID INT,BID INT,DAY VARCHAR(20), FOREIGN KEY(SID) REFERENCES SAILORS(SID),FOREIGN KEY(BID) REFERENCES BOATS(BID));
INSERT INTO SAILORS VALUES(1,'HORATIO',18,10);
INSERT INTO SAILORS VALUES(2,'RAM', 19,11);
INSERT INTO SAILORS VALUES(3,'RAJU',20,8);
INSERT INTO BOATS VALUES(101,'MOTARBOAT','RED');
INSERT INTO BOATS VALUES(102,'SAILORSBOAT','GREEN');
INSERT INTO BOATS VALUES(103,'BOATNAME','BLUE');
INSERT INTO RESERVES VALUES(1,101,'MONDAY');
INSERT INTO RESERVES VALUES(2,102,'TUESDAY');
INSERT INTO RESERVES VALUES(3,103,'FRIDAY');
ALTER TABLE SAILORS
ADD CONSTRAINT UQ_RATING
UNIQUE(RATING);
SELECT * FROM SAILORS WHERE RATING>(SELECT MAX(RATING) FROM SAILORS WHERE SNAME='HORATIO');
SELECT *FROM SAILORS WHERE RATING = (SELECT MAX(RATING) FROM SAILORS);
SELECT S.SNAME FROM SAILORS S JOIN RESERVES R ON S.SID=R.SID
GROUP BY S.SNAME 
HAVING COUNT(R.BID) >=2;
