-- PL/SQL QUESTION
DECLARE
	NUM1 NUMBER:=10;
	NUM2 NUMBER :=20;
	NUM3 NUMBER :=30;
	LARGEST NUMBER;
BEGIN 
	IF (NUM1>=NUM2) AND (NUM1>=NUM3) THEN 
		LARGEST :=NUM1;
	ELSIF (NUM2>=NUM1) AND (NUM2>=NUM3) THEN
		LARGEST :=NUM2;
	ELSE
		LARGEST :=NUM3;
	END IF;
    DBMS_OUTPUT.PUT_LINE('LARGEST NUMBER IS ' || LARGEST);
END;

2,3,4
CREATE TABLE SAILORS(SID INT PRIMARY KEY,SNAME VARCHAR(30),AGE INT,RATING INT);
CREATE TABLE BOATS(BID INT PRIMARY KEY, BNAME VARCHAR(30),COLOR VARCHAR(20));
CREATE TABLE RESERVES(SID INT,BID INT,DAY VARCHAR(20), FOREIGN KEY(SID) REFERENCES SAILORS(SID),FOREIGN KEY(BID) REFERENCES BOATS(BID));
INSERT INTO SAILORS VALUES(1,'KALYAN',18,10);
INSERT INTO SAILORS VALUES(2,'BOB', 19,9);
INSERT INTO SAILORS VALUES(3,'LUBBER',20,8);
INSERT INTO BOATS VALUES(101,'MOTARBOAT','RED');
INSERT INTO BOATS VALUES(102,'SAILORSBOAT','GREEN');
INSERT INTO BOATS VALUES(103,'BOATNAME','BLUE');
INSERT INTO RESERVES VALUES(1,101,'MONDAY');
INSERT INTO RESERVES VALUES(2,102,'TUESDAY');
INSERT INTO RESERVES VALUES(3,103,'FRIDAY');
SELECT B.BNAME FROM BOATS B ,RESERVES R,SAILORS S WHERE B.BID= R.BID AND R.SID= S.SID AND S.SNAME='LUBBER';
SELECT MIN(AGE) AS YOUNG FROM SAILORS ORDER BY RATING;
SELECT AGE FROM SAILORS WHERE SNAME LIKE 'B%' AND SNAME LIKE '%B' AND LENGTH(SNAME) >=3;
DELETE FROM SAILORS WHERE AGE >30 AND RATING <10;
