-- PLSQL
DECLARE 
	NUMDIG NUMBER:=123;
	SUMDIG NUMBER := 0;
	DIGIT NUMBER;
BEGIN
	WHILE NUMDIG>0 LOOP
	DIGIT := MOD(NUMDIG,10);
	SUMDIG := SUMDIG + DIGIT;
	NUMDIG :=FLOOR(NUMDIG/10);
	END LOOP;
	DBMS_OUTPUT.PUT_LINE('SUM IS  ' || SUMDIG);
END;
-- SUM IS  6
CREATE TABLE DEPT(DEPTNO INT,DNAME VARCHAR(12),LOCATION VARCHAR(10));
CREATE TABLE EMP(EMPNO INT,ENAME VARCHAR(20),JOB VARCHAR(10),HIREDATE VARCHAR(20),SALARY INT,DEPTNO INT);
INSERT INTO DEPT VALUES(10,'CSE','NSP');
INSERT INTO DEPT VALUES(20,'ECE','PLK');
INSERT INTO DEPT VALUES(3,'EEE','BHMR');
INSERT INTO EMP VALUES(10,'JOHN','HR','2024-10-11',10000,10);
INSERT INTO EMP VALUES(11,'JACK','ASSI','2023-11-02',20000,20);
INSERT INTO EMP VALUES(12,'JAMES','PROF','2022-10-13',40000,30);
SELECT * FROM EMP WHERE DEPTNO IN(10,20);
SELECT ENAME,SALARY FROM EMP WHERE ENAME LIKE '__A%';
SELECT DEPTNO,AVG(SALARY) FROM EMP 
    GROUP BY DEPTNO
    HAVING AVG(SALARY) >2000;
