-- PLSQL
CREATE OR REPLACE PROCEDURE CIRCLE(RADIUS IN NUMBER,AREA OUT NUMBER,PERIMETER OUT NUMBER) IS
PI CONSTANT NUMBER := 3.14;
BEGIN
	AREA := 3.14*RADIUS*RADIUS;
	PERIMETER := 2*3.14*RADIUS;
	DBMS_OUTPUT.PUT_LINE('AREA IS' || AREA);
	DBMS_OUTPUT.PUT_LINE('PERIMETER IS' || PERIMETER);
END;
-- OUTPUT
-- PROCEDURE CREATED
CREATE TABLE BRANCH (BNAME VARCHAR(20),YOJ INT,INTAKE INT);
CREATE TABLE STUDENT (REGDNO INT,NAME VARCHAR(20),AGE INT,BNAME VARCHAR(20),PERC INT);
INSERT INTO BRANCH VALUES ('CSE', 2008, 200);
INSERT INTO BRANCH VALUES ('IT', 2023, 190);
INSERT INTO BRANCH VALUES ('EEE', 2008, 150);
INSERT INTO STUDENT VALUES (10, 'ANAND', 19, 'CSE', 90);
INSERT INTO STUDENT VALUES (11, 'RAJU', 19, 'IT', 80);
INSERT INTO STUDENT VALUES (12, 'RAMA', 19, 'EEE', 58);
ALTER TABLE BRANCH 
ADD CONSTRAINT PK_BRANCH
PRIMARY KEY(BNAME);
ALTER TABLE STUDENT 
ADD CONSTRAINT PK_REGD_NO
PRIMARY KEY(REGDNO);
ALTER TABLE STUDENT
ADD CONSTRAINT FK_BRANCH
FOREIGN KEY(BNAME) REFERENCES BRANCH(BNAME);
SELECT *FROM STUDENT WHERE NAME LIKE 'A%';
SELECT S.NAME FROM STUDENT S JOIN BRANCH B ON S.BNAME =B.BNAME 
WHERE B.YOJ= 2008;
